(ns more-speech.util.fortune-words)

(def word-map
  {"sweet" ["sour" "pungent" "foul" "bitter" "salty" "fruity"]
   "begins" ["ends" "terminates" "starts" "aborts"]
   "books" ["magazines" "tweets" "pamphlets" "tracts"]
   "air."  ["water" "earth" "fire"]
   "flower" ["tree" "hedge" "shrub" "bush" "weed"]
   "come" ["go" "leave" "enter" "remain"]
   "ability" ["talent" "disability" "skill" "infirmity"]
   "stop" ["go" "resume" "abort"]
   "success" ["failure" "mediocrity"]
   "you’re" ["they're" "we're"]
   "confuse" ["elucidate"]
   "us" ["them"]
   "more" ["less"]
   "hear" ["see" "taste" "smell"]
   "substantial" ["insubstantial" "irrelevant"]
   "talents." ["gifts" "liabilities"]
   "Happy" ["Sad"]
   "lot" ["little"]
   "within" ["around"]
   "confidence" ["trepidation"]
   "parsnips." ["cucumbers" "cabbages" "mushrooms"]
   "going" ["coming"]
   "Diligence" ["Reticence"]
   "New" ["Old"]
   "surprises" ["banalities"]
   "boredom." ["enthusiasm"]
   "acceptance" ["rejection"]
   "Like" ["Love" "Hate" "Indifference"]
   "easy." ["hard"]
   "river" ["lake"]
   "clear." ["cloudy"]
   "light" ["darkness"]
   "his" ["her" "their" "my"]
   "appear" ["vanish"]
   "happiness" ["sadness" "miasma"]
   "trying." ["failing" "waiting"]
   "hell" ["heaven"]
   "later." ["now"]
   "see" ["hear" "taste" "smell" "feel"]
   "precious" ["worthless"]
   "begin" ["end"]
   "faithful" ["faithless"]
   "hard." ["easy" "boring"]
   "learn" ["forget"]
   "logical" ["idiotic"]
   "dance" ["jump" "climb" "run" "sit" "sleep" "scream"]
   "saints" ["devils"]
   "success." ["failure"]
   "right" ["wrong"]
   "warm" ["cool" "hot" "cold" "lukewarm"]
   "today." ["yesterday" "tomorrow" "last week"]
   "started" ["stopped"]
   "twice" ["once" "thrice" "never"]
   "ordinary" ["extraordinary"]
   "next" ["last"]
   "towards" ["away from"]
   "hello" ["goodbye"]
   "friendly" ["hateful"]
   "interesting." ["boring"]
   "high" ["low"]
   "careful" ["careless"]
   "Raise" ["Lower"]
   "weeds." ["flowers" "mushrooms" "trees"]
   "Everyday" ["Sometimes"]
   "Smile" ["Scowl"]
   "forward." ["backward" "sideways"]
   "positive" ["negative" "neutral"]
   "once" ["twice" "not once"]
   "perfect." ["imperfect" "corrupted"]
   "happiness." ["indifference"]
   "up" ["down" "sideways" "around"]
   "food" ["drink"]
   "gratitude" ["ingratitude"]
   "dependable." ["undependable"]
   "laughter." ["howling"]
   "dubious" ["obvious"]
   "emotional" ["logical"]
   "gold" ["silver" "lead" "wood"]
   "three" ["one" "two" "four" "five"]
   "does" ["does not"]
   "heavy" ["light"]
   "disappointed." ["thrilled"]
   "bird" ["dog" "cat" "caterpillar" "spider"]
   "best." ["worst"]
   "worst" ["best"]
   "exciting." ["boring"]
   "pleasantly" ["unpleasantly"]
   "two" ["three" "one" "four" "five"]
   "fresh" ["rotten" "spoiled"]
   "cow" ["dog" "cat" "bird" "horse" "fish"]
   "wink." ["blink" "stare" "weep"]
   "lift" ["lower"]
   "sparkle." ["collapse"]
   "juggle" ["drop"]
   "sinners" ["angels"]
   "mine" ["yours" "his" "hers" "theirs"]
   "insincerity." ["sincerity"]
   "news" ["old news"]
   "lap" ["leg" "arm" "head" "face" "foot"]
   "Nothing" ["Something" "Everything"]
   "chaos." ["order"]
   "happier" ["sadder"]
   "today" ["yesterday" "tomorrow" "next week"]
   "important" ["irrelevant"]
   "smooth" ["rough"]
   "natural" ["unnatural"]
   "fool" ["genius"]
   "far" ["near" "next door"]
   "wisdom" ["idiocy"]
   "Remember" ["Forget"]
   "try" ["fail"]
   "long" ["short"]
   "something" ["nothing" "everything"]
   "wise" ["foolish"]
   "continually" ["never"]
   "soon" ["never"]
   "life." ["death"]
   "hard" ["easy"]
   "second" ["third"]
   "people" ["animals" "plants" "rocks"]
   "good" ["bad"]
   "useless" ["useful"]
   "recklessness" ["care"]
   "moves" ["stays"]
   "new" ["old"]
   "without" ["with"]
   "richness" ["sadness" "penury"]
   "busiest" ["laziest"]
   "smile" ["frown" "grimace"]
   "unrestrained." ["restrained"]
   "tranquility" ["chaos"]
   "pleasure" ["pain"]
   "extravagant" ["ordinary"]
   "wise." ["foolish"]
   "friends" ["enemies"]
   "biggest" ["smallest"]
   "kindness" ["rudeness"]
   "small" ["big"]
   "everywhere." ["nowhere"]
   "leadership" ["cowardice"]
   "adventure" ["boredom"]
   "improvement" ["sabotage"]
   "hand" ["foot" "nose" "ear"]
   "heaven" ["hell" "next door" "Wal-Mart"]
   "luck" ["skill"]
   "should" ["shouldn't"]
   "cannot" ["can"]
   "tomorrow" ["yesterday" "next week" "today"]
   "optimist" ["pessimist"]
   "great" ["small"]
   "talent" ["disability"]
   "short" ["long"]
   "pessimist" ["optimist"]
   "touch" ["feel"]
   "freedom" ["slavery"]
   "greater" ["lesser"]
   "least" ["most"]
   "greatest" ["least"]
   "ground" ["water" "sky"]
   "soul" ["liver" "colon"]
   "persuasive" ["annoying"]
   "garden" ["dumpster"]
   "floating" ["sinking"]
   "can't" ["can"]
   "honorable" ["dishonorable"]
   "friend" ["enemy"]
   "dipped" ["dropped" "raised" ]
   "attracted" ["repelled"]
   "stretched" ["compressed"]
   "enemy" "friend"
   "costly" ["free"]
   "can" ["can't"]
   "foot" ["hand" "head" "nose" "ear" "finger" "toe"]
   "moment" ["week" "year"]
   "unpopular" ["popular"]
   "shrewd" ["dumb"]
   "fall" ["rise" "trip" "stride"]
   "often" ["never"]
   "failure" ["success"]
   "beautiful" ["ugly" "plain"]
   "conquered" ["defeated"]
   "front" ["back"]
   "start" ["end"]
   "largest" ["smallest"]
   "solid" ["liquid"]
   "hands" ["feet" "teeth" "toes" "fingers"]
   "special" ["normal"]
   "won't" ["will"]
   "courage" ["cowardice" "indifference"]
   "true" ["false"]
   "never" ["sometimes" "always"]
   "many" ["some" "few"]
   "walk" ["run" "dance" "trip" "stumble"]
   "love" ["hate"]
   "above" ["below"]
   "deep" ["shallow"]
   "old" ["new"]
   "empty" ["full"]
   "roses" ["daffodils" "sperm whales" "dogs" "cats" "feet"]
   "highest" ["lowest"]
   "unusual" ["normal"]
   "heart" ["liver" "intestines" "colon" "glands"]
   "down" ["up"]
   "bad" ["good"]
   "home" ["Wal-Mart"]
   "one" ["two"]
   "might" ["will"]
   "hate" ["love"]
   "big" ["small"]
   "higher" ["lower"]
   "would" ["wouldn't"]
   "romantic" ["boring"]
   "madness" ["sanity"]
   "can’t" ["can"]
   "soft" ["hard" "rough" "smooth"]
   "now" ["never"]
   "will" ["won't"]
   "strong" ["weak"]
   "modest" ["flagrant"]
   "all" ["few" "some"]
   "large" ["small"]
   "could" ["couldn't"]
   "pleasant" ["unpleasant"]
   "asleep" ["awake"]
   "usually" ["sometimes" "always" "never"]
   "sooner" ["later"]
   "peaceful" ["restless"]
   "behind" ["ahead"]
   "wrong" ["right"]
   "day" ["week" "year" "month" "century"]
   "night" ["day"]
   "patience" ["impatience"]
   "respect" ["loathing"]
   "loved" ["hated"]
   "shall" ["shan't"]
   "before" ["after"]
   "best" ["worst"]
   "nobody" ["everybody" "some"]
   "human" ["canine" "feline"]
   "smart" ["dumb"]
   "little" ["big"]
   "rich" ["poor"]
   "powerful" ["weak"]
   "talents" ["disabilities" "weaknesses"]
   "art" ["doodles" "scribblings"]
   "impatient" ["tolerant"]
   "may" ["will" "won't"]
   "everyone" ["someone" "nobody"]
   "inch" ["foot" "furlong" "mile" "light-year" "millimeter"]
   "stand" ["sit" "sleep"]
   "happy" ["sad" "bored"]
   "done" ["incomplete"]
   "ahead" ["behind"]
   "prosperity" ["poverty"]
   "fire" ["water" "sand" "air" "spit"]
   "fail" ["succeed"]
   "near" ["far"]
   "first" ["second" "third"]
   "strengthen" ["weaken"]
   "extreme" ["normal"]
   "step" ["leap"]
   "pencil" ["pen" "quil" "sword" "tic-tac"]
   "deserve" ["feel" "kick" "pet" "handle" "fondle"]})

(defn change-word [word]
  (let [word-list (get word-map word)
        new-word (if (some? word-list)
                   (rand-nth word-list)
                   word)]
    (if (> 5 (rand-int 10))
      word
      new-word)))

